name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: SharpRDP/SharpRDP.sln  # 修正为实际路径
      Project_Path: SharpRDP/SharpRDP/SharpRDP.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: dotnet publish $env:Project_Path --configuration $env:Configuration --output ./publish
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SharpRDP-Build-${{ matrix.configuration }}
        path: ./publish
